### ISSUE TITLE
Possible bug in ggdag --- internal calls being made without using :: ?

### ISSUE THREAD

**Issue by ben-oneill** [malcolmbarrett/ggdag#53] opened 2021-01-11 23:39 UTC
I have attempted to call some ggdag functions in my function ['plot.data.mappings'](https://github.com/ben-oneill/utilities/blob/main/R/mappings.R).  As you can see from the function, I call a few functions using ggdag::[ggdag function].  This syntax should allow the user to call the functions without loading the ggdag or ggplot2 library, so long as they have those packages installed.  Unfortunately, when I run the function without first loading the libraries (but with the packages installed), I get the following error:

    Error in ggproto(NULL, self, scales = lapply(self$scales, function(s) s$clone())) :   could not find function "ggproto"

I suspect that what is happening is that one of the ggdag functions I am calling is internally calling the function ggproto (from the ggplot2 package), but it is calling it without specifying its package name (i.e., without calling it as ggplot2::ggproto).  If there were an internal call like this in ggdag, it would explain the error message I am getting.  (Note that the error disappears if I load the ggdag and ggplot2 libraries and rerun the function.)

I hope this information is helpful --- please feel free to contact me if you require further details.  I really like your package and think it makes a nice contribution to the field.

**Comment by malcolmbarrett** [comment] 2021-01-11 23:46
duplicate of #45, which will be addressed in #46

**Comment by malcolmbarrett** [comment] 2021-01-11 23:46
Thanks for filing, though!

**Closed by malcolmbarrett** 2021-01-11 23:46 UTC
